#define MQTT_STATUS_TOPIC "smarthome/water-tank/status"
#define MQTT_PUMP_TOPIC "smarthome/water-tank/pump/set"
#define MQTT_OVERFLOW_PUMP_TOPIC "smarthome/water-tank/overflow-pump/set"
#define MQTT_OVERFLOW_PUMP_MODE_TOPIC "smarthome/water-tank/overflow-pump/mode"
#define MQTT_WATER_LEVEL_TOPIC "smarthome/water-tank/water-level"
#define MQTT_SENSOR_MEASURED_DISTANCE_TOPIC "smarthome/water-tank/measured-distance"
#define MQTT_WATER_TEMP_TOPIC "smarthome/water-tank/water/temperature"
#define MQTT_SENSOR_HEIGHT_TOPIC "smarthome/water-tank/water-level/sensor-height"
#define MQTT_OVERFLOW_SENSOR_TOPIC "smarthome/water-tank/water-level/overflow"
#define MQTT_MAX_WATER_LEVEL_TOPIC "smarthome/water-tank/water-level/max-water-level"

#define MQTT_HA_DISCOVERY_WATER_TEMP_TOPIC "homeassistant/sensor/water-tank/water-temperature/config"
#define MQTT_HA_DISCOVERY_PUMP_TOPIC "homeassistant/switch/water-tank/pump/config"
#define MQTT_HA_DISCOVERY_OVERFLOW_PUMP_TOPIC "homeassistant/switch/water-tank/overflow-pump/config"
#define MQTT_HA_DISCOVERY_OVERFLOW_PUMP_MODE_TOPIC "homeassistant/select/water-tank/overflow-pump-mode/config"
#define MQTT_HA_DISCOVERY_WATER_LEVEL_TOPIC "homeassistant/sensor/water-tank/water-level/config"
#define MQTT_HA_DISCOVERY_SENSOR_MEASURED_DISTANCE_TOPIC "homeassistant/sensor/water-tank/measured-distance/config"
#define MQTT_HA_DISCOVERY_CONNECTIVITY_TOPIC "homeassistant/binary_sensor/water-tank/status/config"
#define MQTT_HA_DISCOVERY_SENSOR_LEVEL_TOPIC "homeassistant/number/water-tank/water-level-sensor-height/config"
#define MQTT_HA_DISCOVERY_OVERFLOW_SENSOR_LEVEL_TOPIC "homeassistant/binary_sensor/water-tank/overflow-sensor/config"
#define MQTT_HA_DISCOVERY_MAX_WATER_LEVEL__TOPIC "homeassistant/number/water-tank/max-water-level/config"

#define ONLINE_PAYLOAD "online"
#define OFFLINE_PAYLOAD "offline"

#define ON_PAYLOAD "ON"
#define OFF_PAYLOAD "OFF"
